// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/worker/worker.proto

package file_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskData) Reset() {
	*x = TaskData{}
	mi := &file_pkg_proto_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskData) ProtoMessage() {}

func (x *TaskData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskData.ProtoReflect.Descriptor instead.
func (*TaskData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *TaskData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskData) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_pkg_proto_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_worker_worker_proto protoreflect.FileDescriptor

const file_pkg_proto_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/worker/worker.proto\"<\n" +
	"\bTaskData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"X\n" +
	"\n" +
	"TaskResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage26\n" +
	"\rWorkerService\x12%\n" +
	"\vProcessTask\x12\t.TaskData\x1a\v.TaskResultB5Z3github.com/moevm/grpc_server/pkg/proto/file_serviceb\x06proto3"

var (
	file_pkg_proto_worker_worker_proto_rawDescOnce sync.Once
	file_pkg_proto_worker_worker_proto_rawDescData []byte
)

func file_pkg_proto_worker_worker_proto_rawDescGZIP() []byte {
	file_pkg_proto_worker_worker_proto_rawDescOnce.Do(func() {
		file_pkg_proto_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_worker_worker_proto_rawDesc), len(file_pkg_proto_worker_worker_proto_rawDesc)))
	})
	return file_pkg_proto_worker_worker_proto_rawDescData
}

var file_pkg_proto_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_worker_worker_proto_goTypes = []any{
	(*TaskData)(nil),   // 0: TaskData
	(*TaskResult)(nil), // 1: TaskResult
}
var file_pkg_proto_worker_worker_proto_depIdxs = []int32{
	0, // 0: WorkerService.ProcessTask:input_type -> TaskData
	1, // 1: WorkerService.ProcessTask:output_type -> TaskResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_worker_worker_proto_init() }
func file_pkg_proto_worker_worker_proto_init() {
	if File_pkg_proto_worker_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_worker_worker_proto_rawDesc), len(file_pkg_proto_worker_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_worker_worker_proto_goTypes,
		DependencyIndexes: file_pkg_proto_worker_worker_proto_depIdxs,
		MessageInfos:      file_pkg_proto_worker_worker_proto_msgTypes,
	}.Build()
	File_pkg_proto_worker_worker_proto = out.File
	file_pkg_proto_worker_worker_proto_goTypes = nil
	file_pkg_proto_worker_worker_proto_depIdxs = nil
}
