version: '3.8'

services:
  worker:
    build: 
      context: .
      dockerfile: Dockerfile.hash
    volumes:
      - ./worker/data:/data 
    working_dir: /data
    logging:
      driver: loki 
      options:
          loki-timeout: 10s
          no-file: "true"
          loki-external-labels: "container_name={{.Name}}"
          labels: "container_name, host"
          loki-url:  "http://${LOKI_IP}:${LOG_PORT}/loki/api/v1/push"
