version: '3.3'

services:
  hash:
    build: 
      context: .
      dockerfile: Dockerfile.hash
    container_name: worker
    volumes:
      - ./worker/data:/data 
    working_dir: /data
    logging:
      driver: loki 
      options:
          loki-timeout: 10s
          no-file: "true"
          loki-external-labels: "container_name={{.Name}}"
          labels: "container_name, host"
          loki-url:  "http://${LOKI_IP}:${LOG_PORT}/loki/api/v1/push"
    healthcheck:
      test: ["CMD", "worker", "--status"]
      interval: 30s
      timeout: 5s
      retries: 3
