load("@rules_go//go:def.bzl", "go_library")

go_library(
  name = "binary",
  srcs = ["binary.go"],
  importpath = "github.com/moevm/grpc_server/pkg/binary",
  visibility = ["//visibility:public"],
)
