// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/communication/communication.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PulseType int32

const (
	PulseType_PULSE_REGISTER PulseType = 0
	PulseType_PULSE_OK       PulseType = 1
	PulseType_PULSE_FETCH_ME PulseType = 2
	PulseType_PULSE_SHUTDOWN PulseType = 3
)

// Enum value maps for PulseType.
var (
	PulseType_name = map[int32]string{
		0: "PULSE_REGISTER",
		1: "PULSE_OK",
		2: "PULSE_FETCH_ME",
		3: "PULSE_SHUTDOWN",
	}
	PulseType_value = map[string]int32{
		"PULSE_REGISTER": 0,
		"PULSE_OK":       1,
		"PULSE_FETCH_ME": 2,
		"PULSE_SHUTDOWN": 3,
	}
)

func (x PulseType) Enum() *PulseType {
	p := new(PulseType)
	*p = x
	return p
}

func (x PulseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PulseType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_communication_communication_proto_enumTypes[0].Descriptor()
}

func (PulseType) Type() protoreflect.EnumType {
	return &file_pkg_proto_communication_communication_proto_enumTypes[0]
}

func (x PulseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PulseType.Descriptor instead.
func (PulseType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{0}
}

type ControllerError int32

const (
	ControllerError_CTRL_ERR_OK           ControllerError = 0
	ControllerError_CTRL_ERR_UNKNOWN_TYPE ControllerError = 1
	ControllerError_CTRL_ERR_UNKNOWN_ID   ControllerError = 2
	ControllerError_CTRL_ERR_FAILED       ControllerError = 3
)

// Enum value maps for ControllerError.
var (
	ControllerError_name = map[int32]string{
		0: "CTRL_ERR_OK",
		1: "CTRL_ERR_UNKNOWN_TYPE",
		2: "CTRL_ERR_UNKNOWN_ID",
		3: "CTRL_ERR_FAILED",
	}
	ControllerError_value = map[string]int32{
		"CTRL_ERR_OK":           0,
		"CTRL_ERR_UNKNOWN_TYPE": 1,
		"CTRL_ERR_UNKNOWN_ID":   2,
		"CTRL_ERR_FAILED":       3,
	}
)

func (x ControllerError) Enum() *ControllerError {
	p := new(ControllerError)
	*p = x
	return p
}

func (x ControllerError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerError) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_communication_communication_proto_enumTypes[1].Descriptor()
}

func (ControllerError) Type() protoreflect.EnumType {
	return &file_pkg_proto_communication_communication_proto_enumTypes[1]
}

func (x ControllerError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerError.Descriptor instead.
func (ControllerError) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{1}
}

type ControlType int32

const (
	ControlType_CTRL_RESTART    ControlType = 0
	ControlType_CTRL_FETCH      ControlType = 1
	ControlType_CTRL_SET_TASK   ControlType = 2
	ControlType_CTRL_GET_STATUS ControlType = 3
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0: "CTRL_RESTART",
		1: "CTRL_FETCH",
		2: "CTRL_SET_TASK",
		3: "CTRL_GET_STATUS",
	}
	ControlType_value = map[string]int32{
		"CTRL_RESTART":    0,
		"CTRL_FETCH":      1,
		"CTRL_SET_TASK":   2,
		"CTRL_GET_STATUS": 3,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_communication_communication_proto_enumTypes[2].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_pkg_proto_communication_communication_proto_enumTypes[2]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{2}
}

type WorkerError int32

const (
	WorkerError_WORKER_ERR_OK          WorkerError = 0
	WorkerError_WORKER_ERR_NO_FETCH    WorkerError = 1
	WorkerError_WORKER_ERR_BUSY        WorkerError = 2
	WorkerError_WORKER_ERR_TASK_FAILED WorkerError = 3
	WorkerError_WORKER_ERR_FAILED      WorkerError = 4
)

// Enum value maps for WorkerError.
var (
	WorkerError_name = map[int32]string{
		0: "WORKER_ERR_OK",
		1: "WORKER_ERR_NO_FETCH",
		2: "WORKER_ERR_BUSY",
		3: "WORKER_ERR_TASK_FAILED",
		4: "WORKER_ERR_FAILED",
	}
	WorkerError_value = map[string]int32{
		"WORKER_ERR_OK":          0,
		"WORKER_ERR_NO_FETCH":    1,
		"WORKER_ERR_BUSY":        2,
		"WORKER_ERR_TASK_FAILED": 3,
		"WORKER_ERR_FAILED":      4,
	}
)

func (x WorkerError) Enum() *WorkerError {
	p := new(WorkerError)
	*p = x
	return p
}

func (x WorkerError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerError) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_communication_communication_proto_enumTypes[3].Descriptor()
}

func (WorkerError) Type() protoreflect.EnumType {
	return &file_pkg_proto_communication_communication_proto_enumTypes[3]
}

func (x WorkerError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerError.Descriptor instead.
func (WorkerError) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{3}
}

type WorkerPulse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PulseType              `protobuf:"varint,1,opt,name=type,proto3,enum=PulseType" json:"type,omitempty"`
	WorkerId      uint64                 `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NextPulse     uint64                 `protobuf:"varint,4,opt,name=next_pulse,json=nextPulse,proto3" json:"next_pulse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerPulse) Reset() {
	*x = WorkerPulse{}
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerPulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerPulse) ProtoMessage() {}

func (x *WorkerPulse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerPulse.ProtoReflect.Descriptor instead.
func (*WorkerPulse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerPulse) GetType() PulseType {
	if x != nil {
		return x.Type
	}
	return PulseType_PULSE_REGISTER
}

func (x *WorkerPulse) GetWorkerId() uint64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *WorkerPulse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkerPulse) GetNextPulse() uint64 {
	if x != nil {
		return x.NextPulse
	}
	return 0
}

type PulseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ControllerError        `protobuf:"varint,1,opt,name=error,proto3,enum=ControllerError" json:"error,omitempty"`
	WorkerId      uint64                 `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseResponse) Reset() {
	*x = PulseResponse{}
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseResponse) ProtoMessage() {}

func (x *PulseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseResponse.ProtoReflect.Descriptor instead.
func (*PulseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{1}
}

func (x *PulseResponse) GetError() ControllerError {
	if x != nil {
		return x.Error
	}
	return ControllerError_CTRL_ERR_OK
}

func (x *PulseResponse) GetWorkerId() uint64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type ControlMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlType            `protobuf:"varint,1,opt,name=type,proto3,enum=ControlType" json:"type,omitempty"`
	ExtraSize     uint64                 `protobuf:"varint,2,opt,name=extra_size,json=extraSize,proto3" json:"extra_size,omitempty"`
	TaskId        uint64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMsg) Reset() {
	*x = ControlMsg{}
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMsg) ProtoMessage() {}

func (x *ControlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMsg.ProtoReflect.Descriptor instead.
func (*ControlMsg) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMsg) GetType() ControlType {
	if x != nil {
		return x.Type
	}
	return ControlType_CTRL_RESTART
}

func (x *ControlMsg) GetExtraSize() uint64 {
	if x != nil {
		return x.ExtraSize
	}
	return 0
}

func (x *ControlMsg) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type WorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         WorkerError            `protobuf:"varint,1,opt,name=error,proto3,enum=WorkerError" json:"error,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExtraSize     uint64                 `protobuf:"varint,3,opt,name=extra_size,json=extraSize,proto3" json:"extra_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_communication_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_communication_communication_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerResponse) GetError() WorkerError {
	if x != nil {
		return x.Error
	}
	return WorkerError_WORKER_ERR_OK
}

func (x *WorkerResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkerResponse) GetExtraSize() uint64 {
	if x != nil {
		return x.ExtraSize
	}
	return 0
}

var File_pkg_proto_communication_communication_proto protoreflect.FileDescriptor

const file_pkg_proto_communication_communication_proto_rawDesc = "" +
	"\n" +
	"+pkg/proto/communication/communication.proto\"\x82\x01\n" +
	"\vWorkerPulse\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".PulseTypeR\x04type\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\x04R\bworkerId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x04R\x06taskId\x12\x1d\n" +
	"\n" +
	"next_pulse\x18\x04 \x01(\x04R\tnextPulse\"T\n" +
	"\rPulseResponse\x12&\n" +
	"\x05error\x18\x01 \x01(\x0e2\x10.ControllerErrorR\x05error\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\x04R\bworkerId\"f\n" +
	"\n" +
	"ControlMsg\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.ControlTypeR\x04type\x12\x1d\n" +
	"\n" +
	"extra_size\x18\x02 \x01(\x04R\textraSize\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x04R\x06taskId\"l\n" +
	"\x0eWorkerResponse\x12\"\n" +
	"\x05error\x18\x01 \x01(\x0e2\f.WorkerErrorR\x05error\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x12\x1d\n" +
	"\n" +
	"extra_size\x18\x03 \x01(\x04R\textraSize*U\n" +
	"\tPulseType\x12\x12\n" +
	"\x0ePULSE_REGISTER\x10\x00\x12\f\n" +
	"\bPULSE_OK\x10\x01\x12\x12\n" +
	"\x0ePULSE_FETCH_ME\x10\x02\x12\x12\n" +
	"\x0ePULSE_SHUTDOWN\x10\x03*k\n" +
	"\x0fControllerError\x12\x0f\n" +
	"\vCTRL_ERR_OK\x10\x00\x12\x19\n" +
	"\x15CTRL_ERR_UNKNOWN_TYPE\x10\x01\x12\x17\n" +
	"\x13CTRL_ERR_UNKNOWN_ID\x10\x02\x12\x13\n" +
	"\x0fCTRL_ERR_FAILED\x10\x03*W\n" +
	"\vControlType\x12\x10\n" +
	"\fCTRL_RESTART\x10\x00\x12\x0e\n" +
	"\n" +
	"CTRL_FETCH\x10\x01\x12\x11\n" +
	"\rCTRL_SET_TASK\x10\x02\x12\x13\n" +
	"\x0fCTRL_GET_STATUS\x10\x03*\x81\x01\n" +
	"\vWorkerError\x12\x11\n" +
	"\rWORKER_ERR_OK\x10\x00\x12\x17\n" +
	"\x13WORKER_ERR_NO_FETCH\x10\x01\x12\x13\n" +
	"\x0fWORKER_ERR_BUSY\x10\x02\x12\x1a\n" +
	"\x16WORKER_ERR_TASK_FAILED\x10\x03\x12\x15\n" +
	"\x11WORKER_ERR_FAILED\x10\x04B6Z4github.com/moevm/grpc_server/pkg/proto/communicationb\x06proto3"

var (
	file_pkg_proto_communication_communication_proto_rawDescOnce sync.Once
	file_pkg_proto_communication_communication_proto_rawDescData []byte
)

func file_pkg_proto_communication_communication_proto_rawDescGZIP() []byte {
	file_pkg_proto_communication_communication_proto_rawDescOnce.Do(func() {
		file_pkg_proto_communication_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_communication_communication_proto_rawDesc), len(file_pkg_proto_communication_communication_proto_rawDesc)))
	})
	return file_pkg_proto_communication_communication_proto_rawDescData
}

var file_pkg_proto_communication_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_proto_communication_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_communication_communication_proto_goTypes = []any{
	(PulseType)(0),         // 0: PulseType
	(ControllerError)(0),   // 1: ControllerError
	(ControlType)(0),       // 2: ControlType
	(WorkerError)(0),       // 3: WorkerError
	(*WorkerPulse)(nil),    // 4: WorkerPulse
	(*PulseResponse)(nil),  // 5: PulseResponse
	(*ControlMsg)(nil),     // 6: ControlMsg
	(*WorkerResponse)(nil), // 7: WorkerResponse
}
var file_pkg_proto_communication_communication_proto_depIdxs = []int32{
	0, // 0: WorkerPulse.type:type_name -> PulseType
	1, // 1: PulseResponse.error:type_name -> ControllerError
	2, // 2: ControlMsg.type:type_name -> ControlType
	3, // 3: WorkerResponse.error:type_name -> WorkerError
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_communication_communication_proto_init() }
func file_pkg_proto_communication_communication_proto_init() {
	if File_pkg_proto_communication_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_communication_communication_proto_rawDesc), len(file_pkg_proto_communication_communication_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_communication_communication_proto_goTypes,
		DependencyIndexes: file_pkg_proto_communication_communication_proto_depIdxs,
		EnumInfos:         file_pkg_proto_communication_communication_proto_enumTypes,
		MessageInfos:      file_pkg_proto_communication_communication_proto_msgTypes,
	}.Build()
	File_pkg_proto_communication_communication_proto = out.File
	file_pkg_proto_communication_communication_proto_goTypes = nil
	file_pkg_proto_communication_communication_proto_depIdxs = nil
}
