load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "converter",
    srcs = ["converter.go"],
    importpath = "github.com/moevm/grpc_server/pkg/converter",
    visibility = ["//visibility:public"],
)
