load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "models",
    srcs = ["category.go", "group.go", "provider.go"],
    importpath = "service/internal/models",
    visibility = ["//visibility:public"],
)
