load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "parser",
    srcs = ["json_parser.go"],
    importpath = "github.com/moevm/grpc_server/internal/service/parser",
    visibility = ["//visibility:public"],
)
