// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/proto/file_service/file_service.proto

package file_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_pkg_proto_file_service_file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_file_service_file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_file_service_file_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_pkg_proto_file_service_file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_file_service_file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_file_service_file_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *FileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_file_service_file_service_proto protoreflect.FileDescriptor

const file_pkg_proto_file_service_file_service_proto_rawDesc = "" +
	"\n" +
	")pkg/proto/file_service/file_service.proto\"`\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"W\n" +
	"\fFileResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2:\n" +
	"\vFileService\x12+\n" +
	"\n" +
	"UploadFile\x12\f.FileRequest\x1a\r.FileResponse\"\x00B5Z3github.com/moevm/grpc_server/pkg/proto/file_serviceb\x06proto3"

var (
	file_pkg_proto_file_service_file_service_proto_rawDescOnce sync.Once
	file_pkg_proto_file_service_file_service_proto_rawDescData []byte
)

func file_pkg_proto_file_service_file_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_file_service_file_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_file_service_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_file_service_file_service_proto_rawDesc), len(file_pkg_proto_file_service_file_service_proto_rawDesc)))
	})
	return file_pkg_proto_file_service_file_service_proto_rawDescData
}

var file_pkg_proto_file_service_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_file_service_file_service_proto_goTypes = []any{
	(*FileRequest)(nil),  // 0: FileRequest
	(*FileResponse)(nil), // 1: FileResponse
}
var file_pkg_proto_file_service_file_service_proto_depIdxs = []int32{
	0, // 0: FileService.UploadFile:input_type -> FileRequest
	1, // 1: FileService.UploadFile:output_type -> FileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_file_service_file_service_proto_init() }
func file_pkg_proto_file_service_file_service_proto_init() {
	if File_pkg_proto_file_service_file_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_file_service_file_service_proto_rawDesc), len(file_pkg_proto_file_service_file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_file_service_file_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_file_service_file_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_file_service_file_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_file_service_file_service_proto = out.File
	file_pkg_proto_file_service_file_service_proto_goTypes = nil
	file_pkg_proto_file_service_file_service_proto_depIdxs = nil
}
