FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y \
    build-essential=12.9* \
    cmake=3.22* \
    curl=7.81* \
    git=1:2.34* \
    wget=1.21* \
    meson=0.61* \
    ninja-build=1.10* \
    libssl-dev=3.0* \
    protobuf-compiler=3.12* \
    libprotobuf-dev=3.12* \
    python3=3.10* \
    python3-pip=22.0* \
    libnuma-dev=2.0* \
    pkg-config=0.29* \
    libcurl4-openssl-dev=7.81* \
    libbpf-dev=1:0.5* \
    gcc=4:11* \
    g++=4:11* \
    m4=1.4* \
    libpcap-dev=1.10* \
    libsqlite3-dev=3.37* \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install pyelftools

RUN wget https://github.com/bazelbuild/bazel/releases/download/8.2.1/bazel-8.2.1-linux-x86_64 \
    && chmod +x bazel-8.2.1-linux-x86_64 \
    && mv bazel-8.2.1-linux-x86_64 /usr/local/bin/bazel

RUN wget https://fast.dpdk.org/rel/dpdk-23.11.tar.xz && \
    tar -xf dpdk-23.11.tar.xz && \
    cd dpdk-23.11 && \
    meson setup build --libdir=lib && \
    ninja -C build && \
    ninja -C build install && \
    cd .. && \
    rm -rf dpdk-23.11 dpdk-23.11.tar.xz

ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

WORKDIR /app

COPY scripts/get_prometheus_cpp.sh scripts/
RUN sh scripts/get_prometheus_cpp.sh

COPY ./src/ ./src/
COPY ./include/ ./include/
COPY ./BUILD ./
COPY ./MODULE.bazel ./
COPY ./communication.proto ./
COPY ./toolchains ./toolchains
COPY ./platforms ./platforms
COPY ./third_party ./third_party

RUN bazel build //:worker

WORKDIR /data

RUN ldconfig

ENTRYPOINT ["/app/bazel-bin/worker"]
