FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    wget \
    meson \
    ninja-build \
    libssl-dev \
    protobuf-compiler \
    libprotobuf-dev \
    python3 \
    python3-pip \
    libnuma-dev \
    pkg-config \
    libcurl4-openssl-dev \
    libbpf-dev \
    gcc \
    g++ \
    m4 \
    libpcap-dev \
    libsqlite3-dev \
    libstdc++6 \
    libgcc-s1 \
    libssl3 \
    libcurl4 \
    numactl \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install pyelftools

RUN wget https://github.com/bazelbuild/bazel/releases/download/8.2.1/bazel-8.2.1-linux-x86_64 \
    && chmod +x bazel-8.2.1-linux-x86_64 \
    && mv bazel-8.2.1-linux-x86_64 /usr/local/bin/bazel

RUN wget https://fast.dpdk.org/rel/dpdk-23.11.tar.xz && \
    tar -xf dpdk-23.11.tar.xz && \
    cd dpdk-23.11 && \
    meson setup build --libdir=lib && \
    ninja -C build && \
    ninja -C build install

ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

WORKDIR /app

COPY scripts/get_prometheus_cpp.sh scripts/
RUN sh scripts/get_prometheus_cpp.sh

COPY ./src/ ./src/
COPY ./include/ ./include/
COPY ./BUILD ./
COPY ./MODULE.bazel ./
COPY ./communication.proto ./
COPY ./toolchains ./toolchains
COPY ./platforms ./platforms

RUN bazel build //:worker

WORKDIR /data

RUN ldconfig

ENTRYPOINT ["/app/bazel-bin/worker"]