FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y \
    cmake \
    curl \
    git \
    gnupg \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel-archive-keyring.gpg
RUN mv bazel-archive-keyring.gpg /usr/share/keyrings/
RUN apt-get update && apt-get install -y bazel

WORKDIR /app

RUN  apt install -y gcc-riscv64-linux-gnu
RUN apt-get install -y g++-riscv64-linux-gnu

RUN wget https://www.openssl.org/source/openssl-3.5.0.tar.gz

RUN tar xzf openssl-3.5.0.tar.gz

RUN cd openssl-3.5.0

RUN cd openssl-3.5.0 && chmod +x Configure && \
    ./Configure linux-generic64 \
      --prefix=/usr/riscv64-linux-gnu \
      --cross-compile-prefix=riscv64-linux-gnu- &&\
       make -j$(nproc) &&\
    make install

RUN wget https://github.com/madler/zlib/archive/refs/tags/v1.3.tar.gz
RUN tar -xvzf v1.3.tar.gz
RUN cd zlib-1.3/ &&\
    CHOST=riscv64-linux-gnu ./configure --prefix=/usr/riscv64-linux-gnu &&\
    make -j$(nproc) &&\
    make install 
RUN wget https://curl.se/download/curl-8.8.0.tar.gz
RUN tar -xvzf curl-8.8.0.tar.gz
RUN cd curl-8.8.0 &&\
./configure \
  --host=riscv64-linux-gnu \
  --prefix=/usr/riscv64-linux-gnu \
  --with-openssl=/usr/riscv64-linux-gnu \
  --disable-shared &&\
make -j$(nproc) &&\
make install


RUN wget https://github.com/jupp0r/prometheus-cpp/releases/download/v1.3.0/prometheus-cpp-with-submodules.tar.gz
RUN tar -xvzf prometheus-cpp-with-submodules.tar.gz
RUN rm -rf prometheus-cpp-with-submodules/build && cd prometheus-cpp-with-submodules && \
    mkdir build && cd build && \
    cat <<'EOF' > ../cmake/riscv64-toolchain.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER riscv64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/riscv64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF

RUN cd prometheus-cpp-with-submodules && cd build && cmake .. \
      -DCMAKE_TOOLCHAIN_FILE=../cmake/riscv64-toolchain.cmake \
      -DCMAKE_INSTALL_PREFIX=/usr/riscv64-linux-gnu \
      -DENABLE_TESTING=OFF \
    && make -j$(nproc) \
    && make install

RUN git clone https://github.com/abseil/abseil-cpp.git && \
    cd abseil-cpp && \
    mkdir -p cmake && \
    cat <<'EOF' > cmake/riscv64-toolchain.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER riscv64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/riscv64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF

RUN cd abseil-cpp && \
    mkdir build && cd build && \
    cmake .. \
      -DCMAKE_TOOLCHAIN_FILE=../cmake/riscv64-toolchain.cmake \
      -DCMAKE_INSTALL_PREFIX=/usr/riscv64-linux-gnu \
    && make -j$(nproc) \
    && make install 

RUN git clone --depth 1 --branch v3.21.12 https://github.com/protocolbuffers/protobuf.git && \
    cd protobuf && \
    mkdir -p cmake && \
    cat <<'EOF' > cmake/riscv64-toolchain.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER riscv64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/riscv64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF
RUN cd protobuf && \
    mkdir build && cd build && \
    cmake .. \
      -DCMAKE_TOOLCHAIN_FILE=../cmake/riscv64-toolchain.cmake \
      -DCMAKE_INSTALL_PREFIX=/usr/riscv64-linux-gnu \
      -Dprotobuf_BUILD_TESTS=OFF \
      -DBUILD_SHARED_LIBS=ON && \
    make -j$(nproc) && \
    make install && \
    cd ../.. && rm -rf protobuf


COPY ./src/ ./src/
COPY ./include/ ./include/
COPY ./BUILD ./
COPY ./MODULE.bazel ./
COPY ./communication.proto ./
COPY ./toolchains ./toolchains
COPY ./platforms ./platforms


RUN bazel build //:worker --extra_toolchains=//toolchains/riscv:cc_toolchain_for_linux_riscv64 --platforms=//platforms:riscv64_linux
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    qemu-user-static \
    libc6-riscv64-cross \
    binutils-riscv64-linux-gnu \
    file

COPY --from=builder /app/bazel-bin/worker /usr/local/bin/worker
COPY --from=builder /app/prometheus-cpp-with-submodules/build/lib/ /usr/lib/riscv64-linux-gnu/

COPY --from=builder /usr/riscv64-linux-gnu/lib/libssl.so.3 /usr/lib/riscv64-linux-gnu/
COPY --from=builder /usr/riscv64-linux-gnu/lib/libcrypto.so.3 /usr/lib/riscv64-linux-gnu/
COPY --from=builder /usr/riscv64-linux-gnu/lib/libstdc++.so.6 /usr/lib/riscv64-linux-gnu/
COPY --from=builder /usr/riscv64-linux-gnu/lib/libgcc_s.so.1 /usr/lib/riscv64-linux-gnu/
COPY --from=builder /usr/riscv64-linux-gnu/lib/libatomic.so.1 /usr/lib/riscv64-linux-gnu/

COPY --from=builder /usr/riscv64-linux-gnu/lib/libz.so.1 /usr/lib/riscv64-linux-gnu/

RUN mkdir -p /lib/riscv64-linux-gnu && \
    ln -s /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1 /lib/riscv64-linux-gnu/

RUN ldd /usr/local/bin/worker || true

ENTRYPOINT ["qemu-riscv64-static", "-L", "/usr/riscv64-linux-gnu", "/usr/local/bin/worker", "/data/test.txt", "sha256"]