CC = riscv64-linux-gnu-gcc

DPDK_PREFIX = ./dpdk-riscv-install
PKG_CONFIG = env PKG_CONFIG_LIBDIR=$(DPDK_PREFIX)/lib/pkgconfig pkg-config

CFLAGS = -Iinclude -O2 $(shell $(PKG_CONFIG) --cflags libdpdk)

LDFLAGS = -L$(DPDK_PREFIX)/lib \
          -Wl,--start-group \
          -lrte_eal -lrte_ethdev -lrte_mempool -lrte_mbuf \
          -lrte_bus_vdev \
          -lrte_ring -lrte_telemetry -lrte_kvargs \
          -lrte_log -ldl \
          -Wl,--end-group
          

SRCS = src/dpdk_filter/main.c src/dpdk_filter/af_xdp_port.c
TARGET = main-riscv

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS) $(LDFLAGS)

clean:
	rm -f $(TARGET)

.PHONY: all clean