FROM alpine:3.16.3 AS builder

RUN apk update && apk add --no-cache g++ make cmake openssl-dev curl-dev

WORKDIR /app

COPY get-prometheus-cpp.sh .
RUN sh get-prometheus-cpp.sh

COPY *.cpp *.hpp Makefile ./
RUN make

FROM alpine:3.16.3

RUN apk update &&  apk add --no-cache libstdc++ libgcc libssl3 libcurl

COPY --from=builder /app/hash /usr/local/bin/hash

WORKDIR /data

ENTRYPOINT ["hash"]
