FROM alpine:3.16.3 AS builder

RUN apk update && apk add --no-cache g++ make openssl-dev asio-dev

WORKDIR /app

COPY main.cpp file.hpp file.cpp md_calculator.hpp md_calculator.cpp worker.hpp worker.cpp Makefile ./

RUN make

FROM alpine:3.16.3

RUN apk update &&  apk add --no-cache libstdc++ libgcc libssl3

COPY --from=builder /app/hash /usr/local/bin/hash

WORKDIR /data

ENTRYPOINT ["hash"]
