name: Bazel Worker Build

on: [push]

jobs:
  bazel-worker-build:
    name: Build Worker with Bazel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bazel via Bazelisk
        run: |
          sudo curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel --version

      - name: Build worker
        run: docker compose build
