name: Bazel Worker Build

on: [push]

jobs:
  bazel-worker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bazel via Bazelisk
        run: |
          sudo curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel --version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libgtest-dev cmake build-essential

      - name: Install prometheus-cpp
        run: |
          git clone --depth 1 https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          git submodule update --init --recursive
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build worker
        working-directory: ./worker
        run: bazel build :worker

      - name: Run worker (smoke test)
        working-directory: ./worker
        env:
          METRICS_GATEWAY_ADDRESS: localhost
          METRICS_GATEWAY_PORT: 9091
          METRICS_WORKER_NAME: worker1
        run: |
          timeout 5s bazel run :worker &
          sleep 5
          echo "Worker smoke test completed"