name: Lint check go

on: [push]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install protoc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          protoc --version  # Проверка установки

      - name: Install dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Generate file_service.proto
        working-directory: ./controller
        run: |
          protoc \
            --plugin=protoc-gen-go=$(which protoc-gen-go) \
            --plugin=protoc-gen-go-grpc=$(which protoc-gen-go-grpc) \
            --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            pkg/proto/file_service/file_service.proto
      
      - name: Generate communication.proto
        working-directory: ./controller
        run: |
          protoc \
            --plugin=protoc-gen-go=$(which protoc-gen-go) \
            --plugin=protoc-gen-go-grpc=$(which protoc-gen-go-grpc) \
            --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            pkg/proto/communication/communication.proto

      - name: Run golangci-lint
        working-directory: ./controller
        run: golangci-lint run --timeout 3m
